goog.addDependency("base.js", ['goog'], []);
goog.addDependency("../cljs/core.js", ['cljs.core'], ['goog.string', 'goog.object', 'goog.string.StringBuffer', 'goog.array']);
goog.addDependency("../clojure/string.js", ['clojure.string'], ['goog.string', 'cljs.core', 'goog.string.StringBuffer']);
goog.addDependency("../show/core.js", ['show.core'], ['cljs.core', 'goog.ui.IdGenerator', 'clojure.string']);
goog.addDependency("../plug2/schema.js", ['plug2.schema'], ['cljs.core']);
goog.addDependency("../plug2/events.js", ['plug2.events'], ['cljs.core', 'plug2.schema']);
goog.addDependency("../plug2/types.js", ['plug2.types'], ['cljs.core', 'plug2.events', 'plug2.schema']);
goog.addDependency("../plug2/core.js", ['plug2.core'], ['plug2.types', 'cljs.core', 'plug2.schema']);
goog.addDependency("../show/dom.js", ['show.dom'], ['cljs.core', 'plug2.core']);
goog.addDependency("../examples/basic_plug/core.js", ['examples.basic_plug.core'], ['show.core', 'cljs.core', 'plug2.events', 'plug2.core', 'show.dom']);